package com.guojijian.crm.settings.mapper;

import com.guojijian.crm.settings.pojo.DicValue;
import java.util.List;

public interface DicValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Tue Dec 27 15:31:09 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Tue Dec 27 15:31:09 CST 2022
     */
    int insert(DicValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Tue Dec 27 15:31:09 CST 2022
     */
    DicValue selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Tue Dec 27 15:31:09 CST 2022
     */
    List<DicValue> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Tue Dec 27 15:31:09 CST 2022
     */
    int updateByPrimaryKey(DicValue record);

    /**
     * 根据类型编码查询值
     * @param typeCode
     * @return
     */
    List<DicValue> selectAllDicValueByTypeCode(String typeCode);

    /**
     * 根据id查询value
     */
    String selectValueById(String id);
}